### ISSUE TITLE
default docker-compose.yml doesnt work locally

### ISSUE THREAD

**Issue by ksaadDE** [freescout-helpdesk/freescout#1361]
Hi,

when I try to setup a local installation with docker (the example docker-compose.yml)
It is just redirecting to HTTPS/443 and the container does not have p443 opened, because the webserver runs at p80.

Don't know how to patch it, the structure is crazy inside the app container (nothing against you, it's professionally done except a few things regarding documentation).

Greetz

/E: I was stupid, I've overseen the Letsencrypt properties as well as the encrypted proxy setting...

**Comment by ksaadDE** [comment]
![image](https://user-images.githubusercontent.com/37943746/128262504-642c68b6-f8bb-4309-a1e5-5c39669deb0a.png)
A Screenshot... I've also changed before https to http, but does not work either!

**Comment by ksaadDE** [comment]
cat docker-compose.yml 

```
version: '2'

services:
  
  freescout-app:
    image: tiredofit/freescout
    container_name: freescout-app
    links:
    - freescout-db
    volumes:
    ### If you want to perform customizations to the source and have access to it, then uncomment this line - This includes modules
    #- ./data:/www/html
    ### Or, if you just want to use Stock Freescout and hold onto persistent files like cache and session use this, one or the other.
    - ./data:/data
    ### If you want to just keep the original source and add additional modules uncomment this line
    #- ./modules:/www/html/Modules
    - ./logs/:/www/logs
    environment:
    - VIRTUAL_HOST=freescout.local
    - VIRTUAL_PORT=80
    - ZABBIX_HOSTNAME=freescout-app
    - DB_HOST=freescout-db
    - DB_NAME=freescout
    - DB_USER=freescout
    - DB_PASS=freescout
    - SITE_URL=http://freescout.local
    - ADMIN_EMAIL=admin@admin.com
    - ADMIN_PASS=freescout
    - DISPLAY_ERRORS=FALSE
    - TIMEZONE=Europe/Berlin
    networks:
      - proxy-tier
    restart: always

  freescout-db:
    image: tiredofit/mariadb
    container_name: freescout-db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - ROOT_PASS=password
      - DB_NAME=freescout
      - DB_USER=freescout
      - DB_PASS=freescout

      - ZABBIX_HOSTNAME=freescout-db
    networks:
      - proxy-tier
    restart: always

  freescout-db-backup:
    container_name: freescout-db-backup
    image: tiredofit/db-backup
    links:
     - freescout-db
    volumes:
      - ./dbbackup:/backup
    environment:
      - ZABBIX_HOSTNAMEfreescout-db-backup
      - DB_HOST=freescout-db
      - DB_TYPE=mariadb
      - DB_NAME=freescout
      - DB_USER=freescout
      - DB_PASS=freescout
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - COMPRESSION=BZ
      - MD5=TRUE
    networks:
      - proxy-tier
    restart: always


networks:
  proxy-tier:
    external:
      name: nginx-proxy
```
**Fixed**


**Changes:** 
- removed https from env-vars
- removed  letsencrypt env vars 
- deleted the enabled proxy = yes entry
