### ISSUE TITLE
Fix max-height for notification dropdown on higher screen resolutions

### ISSUE THREAD

**Issue by rutger1140** [freescout-helpdesk/freescout#1517]
When using a window size with more than 1086px in  height the notification dropdown scroll looks weird. It breaks out of the box and the contents show through the box-shadow.

<img width="562" alt="Schermafbeelding 2021-10-27 om 18 07 43" src="https://user-images.githubusercontent.com/357924/139104311-42d2f892-076a-4f18-b8b3-0673ed49f375.png">

This is due to the set max-height of the dropdown-menu. The `.web-notifications-list` has a max-height of `70vh`. The `.dropdown-menu` is set to `800px`. This seems duplicate.

Currently we use this as custom CSS to work around this.
```css
/* Bugfix for max-height of dropdown-menu */
.web-notifications .dropdown-menu {
  max-height: inherit;
}
```
