### ISSUE TITLE
Cannot log in - credentials invalid/user not found

### ISSUE THREAD

**Issue by DerDomml** [freescout-helpdesk/freescout#1771]
Hey folks,

I have just tried to run freescout using the example `docker-compose.yml` file (without proxy). I have adjusted all variables that seemed relevant to me, such as the domain name, admin email and admin password.
When I start the compose it all looks fine.
I then access the website via the domain which works like a charm, try to log in with the credentials specified in the `ADMIN_MAIL` and `ADMIN_PASS` environment variables but freescout tells me `"These credentials do not match our records"`. When I hit `"Forgot your password?"` and enter my email, it tells me no user with that address has been found.

Am I doing something obviously wrong that I cannot see?

My docker-compose.yml looks like this:

```
version: '2'

services:
  freescout-app:
    image: tiredofit/freescout
    container_name: freescout-app
    ports:
    - 80:80
    links:
    - freescout-db
    volumes:
    ### If you want to perform customizations to the source and have access to it, then uncomment this line - This includes modules
    #- ./data:/www/html
    ### Or, if you just want to use Stock Freescout and hold onto persistent files like cache and session use this, one or the other.
    - ./data:/data
    ### If you want to just keep the original source and add additional modules uncomment this line
    - ./modules:/www/html/Modules
    - ./logs/:/www/logs
    environment:
    - CONTAINER_NAME=freescout-app
    - DB_HOST=freescout-db
    - DB_NAME=freescout
    - DB_USER=freescout
    - DB_PASS=freescout
    - SITE_URL=http://myfreescoutserver.net/
    - ADMIN_EMAIL=user@maildomain.com
    - ADMIN_PASS=apassword
    - ENABLE_SSL_PROXY=FALSE
    - DISPLAY_ERRORS=TRUE
    - TIMEZONE=Europe/Berlin
    restart: always
  freescout-db:
    image: tiredofit/mariadb
    container_name: freescout-db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - ROOT_PASS=password
      - DB_NAME=freescout
      - DB_USER=freescout
      - DB_PASS=freescout
      - CONTAINER_NAME=freescout-db
    restart: always
  freescout-db-backup:
    container_name: freescout-db-backup
    image: tiredofit/db-backup
    links:
     - freescout-db
    volumes:
      - ./dbbackup:/backup
    environment:
      - CONTAINER_NAME=freescout-db-backup
      - DB_HOST=freescout-db
      - DB_TYPE=mariadb
      - DB_NAME=freescout
      - DB_USER=freescout
      - DB_PASS=freescout
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - COMPRESSION=BZ
      - MD5=TRUE
    restart: always
```
