### ISSUE TITLE
"Remove formatting" button not working properly on summernote editor

### ISSUE THREAD

**Issue by TangibleMark** [freescout-helpdesk/freescout#2063]
Hi, I have attached a [video](https://www.loom.com/share/703c56a6f6d144af9f73cfe7fa0cef56) showcasing how the "remove formatting" button isn't working properly. You can find this editor in the KnowledgeBase module when writing an article.

another example: 

before remove formatting:
![image (3)](https://user-images.githubusercontent.com/107769311/175370985-d1b20520-ee14-4b33-a3db-fd259770e855.png)
after remove formatting the indent is not removed:
![image (4)](https://user-images.githubusercontent.com/107769311/175371007-20dd2e37-014f-4fcc-b846-d4907258bef7.png)
code view after remove formatting showing the indent is not removed:
![image (5)](https://user-images.githubusercontent.com/107769311/175371024-20db0383-7fa6-432b-8c68-0c86b91d3f3e.png)

Any help with this would be much appreciated.

**Comment by freescout-helpdesk** [comment]
Can you reproduce the issue at https://summernote.org/ ?

**Comment by patacra** [comment]
I know that this issue is closed since a while, but I actually also have problems with the "_Clear formatting_" functionality of Summernote.

"_clear formatting_" works for most inline HTML tags such as these cases:

- `<strong>` or `<b>` : This is **important**
- `<em>` or `<i>` : This is _italic_ text
- `<u>` : This is <u>underlined</u> (gladly not accepted on Github)
- `<code>` : `const regexInteger = /^\d+$/;`
- `<var>` : <var>myVariable</var>
- `<kbd>` : <kbd>Ctrl</kbd> + <kbd>C</kbd> to copy
- `<small>` : <small>Small text</small> (not accepted here, on Github)
- `<sup>` : 10 m<sup>2</sup>
- `<sub>` : H<sub>2</sub>O
- `<ins>` : Summernote is <del>expensive</del> <ins>free</ins>!
- `<s>` (previously `<strike>`) : <s>This text is irrelevant</s> (not equivalent to `<del>`)
- `<span style="color: red">` : The tag is removed, which is great.

But it **does not work** for the following cases:

- `<mark>` : <mark>Stabilo</mark> or <mark class="stabilo-orange">orange</mark>
- `<del>` : Summernote is <del>expensive</del> <ins>free</ins>!
- `<span>`  without `style` attribute :  The span is not removed :-(
- `<span class="custom-class">` : The span is not removed :-(

I also noticed that for some weird reasons, _Summernote_ sometimes takes some of my CSS rules and injects them in inline rules on some unnecessary added `<span>` tags. Example: `<span style="color: var(--color-text,#333); font-family: inherit; font-size: inherit;">`. It seems to happen when I put to cursor somewhere in a line and then press <kbd>Return</kbd> to create a new paragraph. It's difficult for me to know what triggers this strange behavior. I finally have to run my HTML code through a PHP filter to clean things up, by removing empty spans and drop inline styling. But I would be pleased not to save all this crappy HTML code in my database. If someone already implemented a "_clean-up filter_", I would be very pleased to add it to my editor set-up.

You can reproduce the "_Clear formatting_" bugs by pasting this HTML in [Summernote's home-page demo editor](https://summernote.org/):

```html
<p>"<em>Clear formatting</em>" works for most inline HTML tags such as these cases:</p>
<ul>
    <li><code>&lt;strong&gt;</code> or <code>&lt;b&gt;</code> :
        This is <strong>important</strong><br />
        <code>&lt;strong class="very-important"&gt;</code> :
        This is <strong class="very-important">very important</strong>
    </li>
    <li><code>&lt;em&gt;</code> or <code>&lt;i&gt;</code> :
        This is <em>italic</em> text
    </li>
    <li><code>&lt;u&gt;</code> :
        <u>underlined</u> should not be used!
    </li>
    <li><code>&lt;code&gt;</code> :
        <code>const regexInteger = /^\d+$/;</code>
    </li>
    <li><code>&lt;var&gt;</code> :
        <var>myVariable</var>
    </li>
    <li><code>&lt;kbd&gt;</code> :
        <kbd>Ctrl</kbd> + <kbd>C</kbd> to copy
    </li>
    <li><code>&lt;small&gt;</code> :
        <small>Small text</small>
    </li>
    <li><code>&lt;sup&gt;</code> :
        10 m<sup>2</sup>
    </li>
    <li><code>&lt;sub&gt;</code> :
        H<sub>2</sub>O
    </li>
    <li><code>&lt;ins&gt;</code> :
        Summernote is <del>expensive</del> <ins>free</ins>!
    </li>
    <li><code>&lt;s&gt;</code> (previously <code>&lt;strike&gt;</code>) :
        <s>This text is irrelevant</s> (not equivalent to <code>&lt;del&gt;</code>)
    </li>
    <li><code>&lt;span style="color: red"&gt;</code> (with <code>style</code> attribute) :
        The <span style="color: red">span tag</span> is removed, which is great.
    </li>
</ul>

<p>But it <strong>does not work</strong> for the following cases:</p>
<ul>
    <li><code>&lt;mark&gt;</code> or <code>&lt;mark class="stabilo-orange"&gt;</code> :
        <mark>&lt;mark&gt;</mark> or <mark class="stabilo-orange">orange 🍊</mark><br />
    </li>
    <li><code>&lt;del&gt;</code> :
        Summernote is <del>expensive</del> <ins>free</ins>!
    </li>
    <li><code>&lt;span&gt;</code> without any attribute :
        The <span>span element</span> is not removed :-(
    </li>
    <li><code>&lt;span class="pink-panther"&gt;</code> :
        The <span class="pink-panther">pink-panther span</span> is not removed :-(
    </li>
</ul>
```

To see it better, load the following CSS:

```css
code {
    background: #f4f4f4;
    padding: 0 .2em;
}

kbd {
    background: linear-gradient(140deg, #000, #888);
    border-color: #888 #000 #000 #888;
    border-radius: .4em;
    border-style: solid;
    border-width: .1em .1em .2em;
    box-shadow: .1em .1em .1em rgba(0, 0, 0, .2);
    color: #ffffff;
    font: normal 700 .9em monospace;
    padding: .1em .3em 0;
}

mark {
    background-color: rgba(255, 255, 0, 0.5);
    padding: 0 .1em;
    margin: 0 -.1em;
}

mark.stabilo-orange {
    background-color: rgba(255, 123, 0, 0.5);
}

del {
    color: darkred;
}

ins {
    color: darkgreen;
}

strong.very-important {
    --font-size: 1.2;
    font-size: calc(var(--font-size) * 1em);
    line-height: calc(1 / var(--font-size)); /* Compensate the bigger font size */
}

.pink-panther {
    color: darkmagenta;
    border: 1px solid rgb(255, 135, 255);
    border-radius: .2em;
    background-color: rgb(253, 246, 253);
    padding: 0 .2em;
}
```

See it live in this video:

https://github.com/user-attachments/assets/94d425ec-481e-4da9-9fd1-8801dc8db97f
